# Generated by Django 3.1.7 on 2021-04-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20210411_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
