# Generated by Django 3.1.7 on 2021-04-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210411_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
