# Generated by Django 3.2.3 on 2021-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210412_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sin',
        ),
    ]
