# Generated by Django 3.2.3 on 2021-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_student_sin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Lab Assistant', 'Lab Assistant'), ('Marker', 'Marker'), ('Proctor', 'Proctor')], max_length=100, null=True),
        ),
    ]
