# Generated by Django 3.2.3 on 2021-05-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210525_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pay',
            new_name='wage',
        ),
    ]
