# Generated by Django 3.2.3 on 2021-05-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210526_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSheet',
            new_name='TimeSheetEntry',
        ),
        migrations.AlterModelTable(
            name='timesheetentry',
            table='time_sheet_entry',
        ),
    ]
