# Generated by Django 3.2.3 on 2021-05-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210526_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='id_job',
            new_name='job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hazardous',
        ),
        migrations.RemoveField(
            model_name='job',
            name='studentYear',
        ),
    ]
