# Generated by Django 3.2.3 on 2021-05-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_job_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetentry',
            old_name='status',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='timesheetentry',
            old_name='id_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='timesheetentry',
            old_name='dateHours',
            new_name='submitDate',
        ),
    ]
