# Generated by Django 3.2.3 on 2021-05-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210526_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetentry',
            old_name='endTime',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='submitDate',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='timesheetentry',
            constraint=models.UniqueConstraint(fields=('date', 'job', 'start_time', 'end_time'), name='unique_entry'),
        ),
    ]
