# Generated by Django 3.2.3 on 2021-06-16 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20210526_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
