# Generated by Django 3.2.3 on 2021-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
