# Generated by Django 3.2.3 on 2021-06-17 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210616_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job'),
        ),
    ]
