# Generated by Django 3.2.3 on 2021-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210622_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
