# Generated by Django 3.2.3 on 2021-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_student_id_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='sin',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
