# Generated by Django 3.2.3 on 2021-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20210622_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='id_supervisor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
