# Generated by Django 3.2.3 on 2021-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20210622_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
