# Generated by Django 3.2.3 on 2021-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_alter_student_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(max_length=15),
        ),
    ]
