# Generated by Django 3.2.3 on 2021-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20210628_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='id_supervisor',
            field=models.IntegerField(error_messages={'unique': 'Supervisor with this ID is already registered.'}, primary_key=True, serialize=False),
        ),
    ]
