# Generated by Django 3.2.3 on 2021-06-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_alter_supervisor_id_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='id_supervisor',
            field=models.IntegerField(error_messages={'blank': 'Supervior ID is required.', 'unique': 'Supervisor with this ID is already registered.'}, primary_key=True, serialize=False),
        ),
    ]
