# Generated by Django 3.2.3 on 2021-06-29 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_alter_supervisor_id_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.IntegerField(error_messages={'unique': 'Student with this ID is already registered.'}, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='id_supervisor',
            field=models.IntegerField(error_messages={'unique': 'Supervisor with this ID is already registered.'}, primary_key=True, serialize=False),
        ),
    ]
