# Generated by Django 3.2.3 on 2021-06-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_alter_supervisor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
