# Generated by Django 3.2.3 on 2021-07-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_alter_job_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Lab Assistant', 'Lab Assistant'), ('Marker', 'Marker'), ('Proctor', 'Proctor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='job',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.supervisor'),
        ),
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
