# Generated by Django 3.2.3 on 2021-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_auto_20210703_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='job',
            name='dateHours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='job',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='job',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='job',
            name='startTime',
        ),
        migrations.AlterField(
            model_name='job',
            name='season',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6),
        ),
    ]
