# Generated by Django 3.2.3 on 2021-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_alter_job_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('TA', 'Teaching Assistant'), ('Lab Assistant', 'Lab Assistant'), ('Marker', 'Marker'), ('Proctor', 'Proctor')], max_length=100),
        ),
    ]
