# Generated by Django 3.2.3 on 2021-07-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_alter_job_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
