# Generated by Django 3.2.3 on 2021-07-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_auto_20210706_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='dept',
            new_name='department',
        ),
    ]
