# Generated by Django 3.2.3 on 2021-07-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='phone',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
