# Generated by Django 3.2.3 on 2021-07-09 23:08

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to=main_app.models.user_directory_path),
        ),
    ]
