# Generated by Django 3.2.3 on 2021-07-20 19:33

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_alter_supervisor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(default='images/profile_pics/default.png', upload_to=main_app.models.user_directory_path),
        ),
    ]
