# Generated by Django 3.2.3 on 2021-07-21 09:32

from django.db import migrations
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_alter_supervisor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=main_app.models.CustomEmailField(error_messages={'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='email',
            field=main_app.models.CustomEmailField(error_messages={'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
    ]
